// Backward-compatible entry point for existing imports.
export {
  classifyTelegramText,
  completionCard,
  completionActionButtons,
  dailyCoachCard,
  foldedTelegramText,
  formatDailyCoachMessage,
  formatActiveSessionMessage,
  formatStartedSessionMessage,
  formatMinutesShort,
  formatNowCoachMessage,
  formatReplanSummary,
  formatTelegramDate,
  formatTelegramWeek,
  friendlyHelpMessage,
  greetingMessage,
  mainMenuButtons,
  manualTaskChoiceButtons,
  nowCoachCard,
  parseAvailableMinutes,
  parseManualStudyText,
  parseTestResultText,
  recommendationReasonText,
  replanCard,
  testResultPresentation,
  totalCapacityForRemainingAvailability,
  TELEGRAM_BUTTON_LABELS,
  unknownMessage,
  weeklyReportPresentation,
  weeklyStartPresentation,
} from "./telegram-presentation.ts";
export type {
  ParsedTestResult,
  TelegramButton,
  TelegramCardItem,
  TelegramCardMetric,
  TelegramCardModel,
  TelegramIntent,
} from "./telegram-presentation.ts";
