import { useState } from "react";
import { Icon } from "../components/Icon";
import { useLab } from "./context";
import { DAYS, SHORT_DAYS, SUBJECTS, SUBJECT_COLORS, duration, studiedMinutes } from "./model";
import { Badge, Button, PageHeading, Progress, SectionHeading } from "./ui";

export function Insights() {
  const { state, navigate } = useLab();
  const minutes = studiedMinutes(state.tasks);
  const target = state.tasks.reduce((sum, t) => sum + t.minutes, 0);
  const unattended = SUBJECTS.filter((s) => studiedMinutes(state.tasks.filter((t) => t.subject === s)) === 0);
  return <><PageHeading eyebrow="İLERLEME · BU HAFTA" title="Emeğin birikiyor." description="Bir yarış değil. Sana iyi gelen ritmi bulma yolculuğu." /><section className="lab-insight-overview"><div><span className="lab-eyebrow">BU HAFTA ÇALIŞTIĞIN</span><strong>{duration(minutes)}</strong><p>Planındaki hedef: {duration(target)}</p><Progress value={minutes} max={target} label="Haftalık çalışma ilerlemesi" /><span className="lab-muted">Planının %{target ? Math.round(minutes / target * 100) : 0}’i tamamlandı.</span></div><div className="lab-insight-verdict"><Badge tone="success">Düzenli bir başlangıç</Badge><h2>Ritmin var.<br />Şimdi denge zamanı.</h2><p>{unattended.length ? `${unattended.length} derste henüz çalışman yok. Kalan günlerde ${unattended.join(" ve ")} için ayırdığın zamanı koru.` : "Bu hafta her dersine zaman ayırdın. Kalan çalışmalarını aynı dengede sürdürebilirsin."}</p></div></section><div className="lab-insights-grid"><section className="lab-surface"><SectionHeading title="Gün gün emeğin" aside={<span className="lab-muted">Dakika</span>} /><div className="lab-week-chart">{DAYS.map((d, i) => { const value = studiedMinutes(state.tasks.filter((t) => t.day === i)); return <div key={d}><strong>{Math.round(value)}</strong><div className="lab-bar-track"><i style={{ height: `${Math.max(2, value / Math.max(120, ...DAYS.map((_, index) => studiedMinutes(state.tasks.filter((t) => t.day === index)))) * 100)}%` }} /></div><span>{SHORT_DAYS[i]}</span></div>; })}</div></section><section className="lab-surface"><SectionHeading title="Derslerin dengesi" />{SUBJECTS.map((s) => { const subset = state.tasks.filter((t) => t.subject === s); return <div className="lab-subject-progress" key={s}><div><span><i style={{ background: SUBJECT_COLORS[s] }} />{s}</span><strong>{duration(studiedMinutes(subset))}</strong></div><Progress value={studiedMinutes(subset)} max={subset.reduce((sum, t) => sum + t.minutes, 0)} label={`${s} haftalık ilerleme`} /></div>; })}</section></div><section className="lab-inline-coach"><Icon name="spark" /><div><span className="lab-eyebrow">KOÇUNUN ÖNERİSİ</span><h3>İktisat için ayırdığın zamanı koru.</h3><p>Bugünkü video dersi, haftanın dengesi için iyi bir başlangıç.</p></div><Button tone="secondary" onClick={() => navigate("today")}>Bugünkü planıma git</Button></section><details className="lab-records"><summary>Çalışma kayıtlarını gör</summary><ul>{state.tasks.filter((t) => t.studiedSeconds > 0).map((t) => <li key={t.id}><span>{DAYS[t.day]} · {t.subject} · {t.title}</span><strong>{duration(t.studiedSeconds / 60)}</strong></li>)}</ul></details></>;
}
const MONTHS = [
  { name: "Ekim", stage: "Temeli sağlamlaştır", hours: 110, begin: "Maliye Ders Notları", end: "Matematik · Temel kavramlar", milestone: "Beş derste düzenli çalışma ritmi", description: "Muhasebe ve matematikte başladığın konuları ilerlet. İktisat ve maliyeyi haftanın doğal bir parçası yap.", risk: "İktisatta düzenli çalışma başlamazsa kasım yükün artabilir." },
  { name: "Kasım", stage: "Konuları birbirine bağla", hours: 115, begin: "Muhasebe soru çözümü", end: "Reditus Muhasebe · Konu anlatımı", milestone: "İlk kapsamlı konu tekrarı", description: "Bitirdiğin konuları soru çözümüyle pekiştir. Yanlışların tekrar sırasını belirlesin.", risk: "" },
  { name: "Aralık", stage: "Bilgiyi uygulamaya geçir", hours: 100, begin: "Karma soru setleri", end: "Matematik Soru Bankası", milestone: "İlk branş denemesi", description: "Soru çeşitliliğini artır. Her derste güçlü ve eksik konularını daha net gör.", risk: "Okul sınavları için haftalık sürede esneklik bırak." },
  { name: "Ocak", stage: "Eksikleri görünür yap", hours: 105, begin: "Branş denemeleri", end: "İktisat Konu Anlatımı", milestone: "İlk genel değerlendirme", description: "Deneme sonuçlarına göre eksik konulara geri dön. Tekrarlarını küçük parçalara ayır.", risk: "" },
];
export function Roadmap() {
  const { navigate } = useLab();
  const [selected, setSelected] = useState(0);
  const month = MONTHS[selected]!;
  return <><PageHeading eyebrow="YOL HARİTASI · HAZIRLIK DÖNEMİN" title="Her ay, hedefe biraz daha yakın." description="Önce temel, sonra uygulama, ardından deneme ve tekrar." /><section className="lab-roadmap-summary"><Icon name="target" size={28} /><div><strong>KPSS P48 · 2027 hazırlığı</strong><p>Şu an temel oluşturma aşamasındasın.</p></div><Badge tone="success">1. aşama / 3</Badge></section><nav className="lab-months" aria-label="Hazırlık ayları">{MONTHS.map((m, i) => <button key={m.name} aria-pressed={selected === i} onClick={() => setSelected(i)}><span className="lab-month-dot">{i === 0 ? <span /> : i + 1}</span><strong>{m.name}</strong><span>{i === 0 ? "Şu an buradasın" : `${m.hours} sa · tahmini`}</span></button>)}</nav><section className="lab-month-detail"><div><span className="lab-eyebrow">{month.name.toLocaleUpperCase("tr-TR")} · {month.hours} SAAT TAHMİNİ ÇALIŞMA</span><h2>{month.stage}.</h2><p>{month.description}</p><Button tone="secondary" onClick={() => navigate("week")}>Bu haftaki adımlarım <Icon name="arrow" size={16} /></Button></div><dl><div><dt>Başlayacak kaynak</dt><dd>{month.begin}</dd></div><div><dt>Tamamlanacak bölüm / kaynak</dt><dd>{month.end}</dd></div><div><dt>Ayın kilometre taşı</dt><dd><Icon name="target" size={18} />{month.milestone}</dd></div></dl></section>{month.risk && <div className="lab-roadmap-risk"><Icon name="warning" /><div><strong>Biraz dikkat</strong><p>{month.risk}</p></div></div>}<section className="lab-roadmap-later"><span>ŞUBAT — MAYIS</span><h3>Denemeler ve eksik konular</h3><p>Sonuçlarına göre tekrarlarını şekillendir.</p><span>HAZİRAN — SINAV</span><h3>Son tekrar ve sınav ritmi</h3><p>Süreli denemeler, kısa tekrarlar ve sürdürülebilir tempo.</p></section><p className="lab-footnote">Bu yol haritası örnek bir hazırlık takvimidir. Resmî sınav tarihi veya kesin bitiş sözü içermez.</p></>;
}
