import { useEffect, useState } from "react";
import { Icon } from "../components/Icon";
import { useLab } from "./context";
import { SUBJECTS, SUBJECT_COLORS, clockTime, type Material } from "./model";
import { Badge, Button, EmptyState, Modal, PageHeading, Progress, Skeleton } from "./ui";

const STATUS = { active: "Aktif", queued: "Sırada", waiting: "Beklemede" } as const;
export function Resources() {
  const { state, resource } = useLab();
  const [category, setCategory] = useState("Tümü");
  const materials = state.materials.filter((m) => category === "Tümü" || m.subject === category);
  return <><PageHeading eyebrow="KAYNAKLARIM" title="Nerede kaldığın hep belli." description="Kitapların, video derslerin ve sıradaki kaynakların bir arada." /><nav className="lab-filter" aria-label="Kaynak dersi">{["Tümü", ...SUBJECTS].map((subject) => <button key={subject} aria-pressed={subject === category} onClick={() => setCategory(subject)}>{subject}</button>)}</nav><div className="lab-resource-grid">{materials.map((material) => <article key={material.id} className="lab-resource-card"><div className="lab-resource-cover" style={{ color: SUBJECT_COLORS[material.subject] }}><Icon name={material.kind === "video" ? "play" : "book"} size={30} /><span>{material.subject}</span></div><div className="lab-resource-info"><div className="lab-resource-labels"><span className="lab-meta">{material.kind === "video" ? "YOUTUBE DERS SERİSİ" : "FİZİKSEL KİTAP"}</span><Badge tone={material.status === "active" ? "success" : "neutral"}>{STATUS[material.status]}</Badge></div><h2>{material.name}</h2><p>{material.note}</p><div className="lab-progress-label"><span>{material.progress} / {material.total} {material.kind === "video" ? "video" : "sayfa"}</span><strong>%{Math.round(material.progress / material.total * 100)}</strong></div><Progress value={material.progress} max={material.total} label={`${material.name} ilerlemesi`} /><div className="lab-resource-bottom"><span className="lab-muted">Tahmini bitiş · {material.estimate}</span><button className="lab-text-link" onClick={() => resource(material)}>{material.kind === "video" ? "İzlemeye devam et" : "Kaynağı aç"}<Icon name="arrow" size={16} /></button></div></div></article>)}</div>{!materials.length && <EmptyState title="Burada henüz kaynak yok." description="Diğer derslerdeki kaynaklarına bakabilirsin."><Button tone="secondary" onClick={() => setCategory("Tümü")}>Tüm dersler</Button></EmptyState>}<p className="lab-footnote">Bitiş zamanları çalışma hızına göre değişen tahminlerdir.</p></>;
}
export function ResourceDetail({ material, position, onPosition, onClose, onStudy }: { material: Material; position: number; onPosition: (seconds: number) => void; onClose: () => void; onStudy: () => void }) {
  const [loading, setLoading] = useState(material.kind === "video");
  const [playing, setPlaying] = useState(false);
  const totalSeconds = 49 * 60 + 4;
  useEffect(() => { const timer = window.setTimeout(() => setLoading(false), 600); return () => window.clearTimeout(timer); }, []);
  useEffect(() => { if (!playing || position >= totalSeconds) return; const timer = window.setTimeout(() => onPosition(Math.min(totalSeconds, position + 1)), 1000); return () => window.clearTimeout(timer); }, [playing, position, onPosition]);
  return <Modal title="Kaynak ayrıntısı" kind="drawer" onClose={onClose}><div className="lab-dialog-content"><Badge tone={material.status === "active" ? "success" : "neutral"}>{STATUS[material.status]}</Badge><h2>{material.name}</h2><p className="lab-muted">{material.note}</p>{material.kind === "video" ? <>
    {loading ? <Skeleton label="Video alanı hazırlanıyor" /> : <section className="lab-video-player"><span className="lab-eyebrow">İZLEMEYE DEVAM ET</span><div className="lab-video-poster"><span>DERS 13</span><h3>Arz, talep ve<br />piyasa dengesi</h3><Button tone="secondary" icon={playing ? "stop" : "play"} onClick={() => { if (position >= totalSeconds) onPosition(0); setPlaying((v) => !v); }}>{playing ? "Duraklat" : position >= totalSeconds ? "Yeniden oynat" : "Devam et"}</Button></div><div className="lab-video-position"><strong>{clockTime(position)}</strong><span>/ 49:04 · Bu video</span></div><label className="lab-sr-only" htmlFor="lab-video-position">Videoda bulunduğun saniye</label><input id="lab-video-position" className="lab-video-range" type="range" min={0} max={totalSeconds} value={position} onChange={(e) => onPosition(Number(e.target.value))} /><p className="lab-muted lab-small">Örnek oynatıcı: zaman ve kontroller simüle edilir; ses ve görüntü oynatılmaz.</p></section>}
    <section className="lab-playlist-progress"><h3>Ders serisindeki ilerlemen</h3><p><strong>{material.progress} / {material.total}</strong> video tamamlandı</p><Progress value={material.progress} max={material.total} label="Tamamlanan video sayısı" /><p className="lab-muted lab-small">İzleme konumu ile tamamladığın video sayısı ayrı kaydedilir.</p></section>
  </> : <section className="lab-book-detail"><Icon name="book" size={40} /><span className="lab-eyebrow">KALDIĞIN SAYFA</span><strong>{material.progress}<small> / {material.total}</small></strong><Progress value={material.progress} max={material.total} label="Kitap ilerlemesi" /><p>Tahmini bitiş · {material.estimate}</p></section>}
    <div className="lab-resource-next"><h3>Sıradaki adım</h3><p>{material.status === "waiting" ? "Önce konu anlatımını tamamla. Bu kaynağı haftana daha sonra ekleyebilirsin." : material.kind === "video" ? "Video dersini çalışmaya başla; bitirdiğinde tamamladığın son videoyu kaydet." : `${material.progress + 1}. sayfadan devam et. Çalışmayı bitirirken kaldığın sayfayı kaydetmen yeterli.`}</p><Button icon={material.status === "waiting" ? "calendar" : "play"} onClick={onStudy}>{material.status === "waiting" ? "Haftamı aç" : "Çalışmaya başla"}</Button></div>
  </div></Modal>;
}
