import {useCallback,useEffect,useState,type FormEvent} from "react";import{AppApiError,callAppApi,FRIENDLY_API_ERRORS}from"../lib/app-api";
interface Projection{completed:number;inProgress:number;remaining:number;status:string;projectedCompletionDate:string|null;message:string}
type Backlog={open_task_count:number;estimated_remaining_minutes:number;severity:string}|null;
type Revision={explanation:string}|null;
interface Minimum{availableMinutes:number;totalMinutes:number;reason:string;tasks:Array<{id:string;title:string;minutes:number}>}
const errorText=(e:unknown)=>e instanceof AppApiError?(FRIENDLY_API_ERRORS[e.code]??e.message):e instanceof Error?e.message:"İşlem başarısız.";
export function AdaptivePlanningPanel(){const[projection,setProjection]=useState<Projection|null>(null);const[backlog,setBacklog]=useState<Backlog>(null);const[revision,setRevision]=useState<Revision>(null);const[risks,setRisks]=useState<Array<{id:string;message:string;severity:string}>>([]);const[minimum,setMinimum]=useState<Minimum|null>(null);const[error,setError]=useState<string|null>(null);const[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const[p,b,r,pr,m]=await Promise.all([callAppApi<Projection>("/progress/projection"),callAppApi<Backlog>("/backlog/current"),callAppApi<Array<{id:string;message:string;severity:string}>>("/plans/risks"),callAppApi<Revision>("/plan-revisions/latest"),callAppApi<Minimum>("/plans/minimum-day")]);setProjection(p);setBacklog(b);setRisks(r);setRevision(pr);setMinimum(m);setError(null);}catch(e){setError(errorText(e));}},[]);useEffect(()=>{void load();},[load]);
 async function replan(trigger="manual_request"){setBusy(true);try{await callAppApi("/plans/current/recalculate",{method:"POST",body:{trigger}});await load();window.dispatchEvent(new Event("kpss:execution-changed"));}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 async function special(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,fields=new FormData(form),mode=String(fields.get("mode")),value=Number(fields.get("minutes")),normal=minimum?.availableMinutes??0;setBusy(true);try{await callAppApi("/schedule-exceptions",{method:"POST",body:{date:new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul"}).format(new Date()),type:mode==="extra_available"?"extra_available":"custom",minutesDelta:mode==="extra_available"?value:value-normal,note:"Web özel durum"}});await replan("capacity_change");form.reset();}catch(e){setError(errorText(e));setBusy(false);}}
 return <section className="adaptive-panel"><h2>YETİŞİYOR MUYUM?</h2>{error&&<p className="error">{error}</p>}{projection&&<><dl className="stats"><div><dt>Durum</dt><dd>{projection.status}</dd></div><div><dt>Mevcut tahmin</dt><dd>{projection.projectedCompletionDate??"Veri toplanıyor"}</dd></div><div><dt>Tamamlanan / Devam / Eksik</dt><dd>{projection.completed} / {projection.inProgress} / {projection.remaining}</dd></div></dl><p>{projection.message}</p></>}
 <div className="adaptive-grid"><article><h3>BACKLOG</h3><p>{backlog?`${backlog.open_task_count} görev · ${Math.floor(backlog.estimated_remaining_minutes/60)}s ${backlog.estimated_remaining_minutes%60}dk`:"Henüz hesaplanmadı"}</p><strong>{backlog?.severity?.toUpperCase()}</strong>{risks.map(r=><p className="error" key={r.id}>{r.message}</p>)}</article><article><h3>MINIMUM PLAN</h3><p>{minimum?.totalMinutes??0} dk / {minimum?.availableMinutes??0} dk</p><ul>{minimum?.tasks.map(t=><li key={t.id}>{t.title} — {t.minutes} dk</li>)}</ul></article></div>
 <form className="special-form" onSubmit={special}><h3>Bugünkü özel durum</h3><select name="mode"><option value="less">Bugün daha az vaktim var</option><option value="extra_available">Ekstra vaktim var</option></select><label>Dakika<input name="minutes" min="0" type="number" required/></label><button disabled={busy}>Kaydet ve Planı Güncelle</button></form>
 <button className="primary-action" disabled={busy} onClick={()=>void replan()}>Planı Yeniden Hesapla</button>{revision&&<p><strong>Plan neden değişti?</strong> {revision.explanation}</p>}</section>}
