import { randomUUID } from "node:crypto";
import { createClient, type SupabaseClient, type User } from "@supabase/supabase-js";
import { buildRevisionDecision, evaluateTopicMastery } from "@kpss-coach/domain";
import { beforeAll, describe, expect, it } from "vitest";

const url=process.env.SUPABASE_URL, anonKey=process.env.SUPABASE_ANON_KEY;
if(!url||!anonKey)throw new Error("Supabase env required");
const EDITION="11000000-0000-0000-0000-000000000001",MATH="20000000-0000-0000-0000-000000000002",TOPIC="30000000-0000-0000-0000-000000000001",WEAK_TOPIC="30000000-0000-0000-0000-000000000002";
const client=()=>createClient(url!,anonKey!,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
async function register(api:SupabaseClient):Promise<User>{const id=randomUUID();const result=await api.auth.signUp({email:`p5-${id}@example.test`,password:`Safe-${id}`});expect(result.error).toBeNull();return result.data.user!;}

describe("Phase 05 mastery, revision and RLS",()=>{
 const a=client(),b=client();let ua:User,profile:string,firstResult:string,secondResult:string,revisionId:string;
 beforeAll(async()=>{ua=await register(a);await register(b);const p=await a.from("exam_profiles").insert({user_id:ua.id,exam_edition_id:EDITION,preparation_start_date:"2026-08-01",status:"active"}).select("id").single();expect(p.error).toBeNull();profile=p.data!.id;expect((await a.from("user_subjects").insert({user_id:ua.id,exam_profile_id:profile,subject_id:MATH,status:"active"})).error).toBeNull();expect((await a.rpc("initialize_subject_progress",{p_exam_profile_id:profile,p_subject_id:MATH})).error).toBeNull();});

 async function record(topic:string,correct:number,wrong:number,blank=0){const result=await a.rpc("record_test_result",{p_payload:{examProfileId:profile,subjectId:MATH,curriculumNodeId:topic,correct,wrong,blank,total:correct+wrong+blank,entrySource:"web",idempotencyKey:`p5-${randomUUID()}`}});expect(result.error).toBeNull();return result.data;}
 async function assess(sourceId:string,triggerType:"test_result"|"revision_result"|"manual_recalculation"="test_result"){
  const progress=await a.from("topic_progress").select("state,mastery_level,total_questions,last_practiced_at").eq("exam_profile_id",profile).eq("curriculum_node_id",TOPIC).single();
  const rows=await a.from("test_results").select("id,correct_count,wrong_count,blank_count,total_questions,completed_at,updated_at,review_status").eq("exam_profile_id",profile).eq("curriculum_node_id",TOPIC).order("completed_at",{ascending:false}).limit(3);
  const schedules=await a.from("revision_schedules").select("id,status,revision_number,scheduled_for").eq("exam_profile_id",profile).eq("curriculum_node_id",TOPIC);
  expect(progress.error??rows.error??schedules.error).toBeNull();
  const source=rows.data!.find(row=>row.id===sourceId)!;
  const mastery=evaluateTopicMastery({recentTestResults:rows.data!.map(row=>({correct:row.correct_count,wrong:row.wrong_count,blank:row.blank_count,total:row.total_questions,completedAt:row.completed_at})),totalQuestionCount:progress.data!.total_questions,currentMasteryLevel:progress.data!.mastery_level,topicState:progress.data!.state});
  const revision=buildRevisionDecision({masteryLevel:mastery.resultingMasteryLevel,topicState:mastery.resultingTopicState,latestAssessment:mastery,previousRevisionSchedules:schedules.data!.map(row=>({id:row.id,status:row.status,revisionNumber:row.revision_number,scheduledFor:row.scheduled_for})),lastPracticedAt:progress.data!.last_practiced_at,pendingWrongReview:rows.data!.some(row=>row.review_status==="pending"),today:"2026-08-08"});
  const applied=await a.rpc("apply_topic_mastery_assessment",{p_payload:{examProfileId:profile,curriculumNodeId:TOPIC,triggerType,sourceTestResultId:source.id,sourceResultUpdatedAt:source.updated_at,sampleQuestionCount:mastery.sampleQuestionCount,sampleCorrectCount:mastery.sampleCorrectCount,sampleWrongCount:mastery.sampleWrongCount,sampleBlankCount:mastery.sampleBlankCount,previousMasteryLevel:mastery.previousMasteryLevel,resultingMasteryLevel:mastery.resultingMasteryLevel,resultingTopicState:mastery.resultingTopicState,assessmentReason:mastery.reason,revision}});expect(applied.error).toBeNull();return applied.data;
 }

 it("keeps mastery unknown below minimum evidence",async()=>{const result=await record(TOPIC,10,0);firstResult=result.id;const applied=await assess(result.id);expect(applied.assessment.resulting_mastery_level).toBe("unknown");expect(applied.revision).toBeNull();});
 it("classifies sufficient evidence and learns the topic",async()=>{const result=await record(TOPIC,8,2);secondResult=result.id;const applied=await assess(result.id);expect(applied.assessment.resulting_mastery_level).toBe("strong");expect(applied.topicProgress.state).toBe("learned");expect(applied.revision).not.toBeNull();revisionId=applied.revision.id;});
 it("creates one active wrong-review schedule",async()=>{const rows=await a.from("revision_schedules").select("id,revision_type,status").eq("curriculum_node_id",TOPIC).in("status",["scheduled","due"]);expect(rows.data).toHaveLength(1);expect(rows.data![0]).toMatchObject({id:revisionId,revision_type:"wrong_review"});});
 it("hides assessments and revisions from User B",async()=>{expect((await b.from("topic_assessments").select("id")).data).toEqual([]);expect((await b.from("revision_schedules").select("id")).data).toEqual([]);});
 it("correction recomputes mastery with hysteresis and does not duplicate active revision",async()=>{expect((await a.rpc("update_test_result",{p_result_id:firstResult,p_correct:0,p_wrong:10,p_blank:0,p_total:10,p_duration:null})).error).toBeNull();const applied=await assess(firstResult,"manual_recalculation");expect(applied.assessment.resulting_mastery_level).toBe("sufficient");expect(applied.revision.id).toBe(revisionId);expect((await a.from("revision_schedules").select("id",{count:"exact",head:true}).in("status",["scheduled","due"])).count).toBe(1);});
 it("classifies weak evidence as remediation on another topic",async()=>{const result=await record(WEAK_TOPIC,10,10);const progress=await a.from("topic_progress").select("state,mastery_level,total_questions,last_practiced_at").eq("exam_profile_id",profile).eq("curriculum_node_id",WEAK_TOPIC).single();const mastery=evaluateTopicMastery({recentTestResults:[{correct:10,wrong:10,blank:0,total:20,completedAt:result.completed_at}],totalQuestionCount:progress.data!.total_questions,currentMasteryLevel:progress.data!.mastery_level,topicState:progress.data!.state});expect(mastery.resultingMasteryLevel).toBe("critical");expect(mastery.resultingTopicState).toBe("remediation");});
 it("blocks User B revision completion",async()=>{const result=await b.rpc("complete_revision",{p_revision_id:revisionId});expect(result.error?.message).toContain("REVISION_NOT_FOUND");});
 it("completes revision idempotently and updates last revision",async()=>{const first=await a.rpc("complete_revision",{p_revision_id:revisionId});const second=await a.rpc("complete_revision",{p_revision_id:revisionId});expect(first.error??second.error).toBeNull();expect(second.data.status).toBe("completed");const progress=await a.from("topic_progress").select("last_revision_at,state").eq("exam_profile_id",profile).eq("curriculum_node_id",TOPIC).single();expect(progress.data!.last_revision_at).toBeTruthy();expect(progress.data!.state).toBe("maintenance");});
 it("revision result creates a new assessment and next revision",async()=>{const result=await record(TOPIC,10,0);const applied=await assess(result.id,"revision_result");expect(applied.assessment.trigger_type).toBe("revision_result");expect(applied.revision.revision_number).toBe(2);expect(applied.revision.id).not.toBe(revisionId);});
 it("keeps source-version retries idempotent",async()=>{const before=await a.from("topic_assessments").select("id",{count:"exact",head:true});const applied=await assess(secondResult);const after=await a.from("topic_assessments").select("id",{count:"exact",head:true});expect(applied.idempotent).toBe(true);expect(after.count).toBe(before.count);});
});
