import { randomUUID } from "node:crypto";
import { createClient, type SupabaseClient, type User } from "@supabase/supabase-js";
import { beforeAll, describe, expect, it } from "vitest";

const url=process.env.SUPABASE_URL, anonKey=process.env.SUPABASE_ANON_KEY, serviceRoleKey=process.env.SUPABASE_SERVICE_ROLE_KEY;
if(!url||!anonKey||!serviceRoleKey) throw new Error("Supabase env required");
const EDITION="11000000-0000-0000-0000-000000000001", MATH="20000000-0000-0000-0000-000000000002", TOPIC="30000000-0000-0000-0000-000000000001";
const client=()=>createClient(url!,anonKey!,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
async function register(api:SupabaseClient):Promise<User>{const u=randomUUID();const r=await api.auth.signUp({email:`p4-${u}@example.test`,password:`Safe-${u}`});expect(r.error).toBeNull();return r.data.user!;}

describe("Phase 04 execution, results, messaging RLS",()=>{
 const a=client(),b=client(),admin=createClient(url!,serviceRoleKey!,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}); let ua:User,ub:User,profile:string,learn:string,solve:string,otherSolve:string,resource:string,otherResource:string,units:string[],otherUnit:string,session:string,resultId:string;
 beforeAll(async()=>{
  ua=await register(a);ub=await register(b);
  const p=await a.from("exam_profiles").insert({user_id:ua.id,exam_edition_id:EDITION,preparation_start_date:"2026-08-01",status:"active"}).select("id").single();profile=p.data!.id;
  await a.from("user_subjects").insert({user_id:ua.id,exam_profile_id:profile,subject_id:MATH,status:"active"});
  await a.rpc("initialize_subject_progress",{p_exam_profile_id:profile,p_subject_id:MATH});
  const res=await a.from("resources").insert({user_id:ua.id,exam_profile_id:profile,subject_id:MATH,name:"Test Book",resource_type:"question_bank",resource_role:"primary",difficulty:"normal",status:"active"}).select("id").single();resource=res.data!.id;
  const sec=await a.from("resource_sections").insert({resource_id:resource,curriculum_node_id:TOPIC,name:"Temel",sort_order:1}).select("id").single();
  const us=await a.from("resource_units").insert([1,2].map(n=>({resource_id:resource,resource_section_id:sec.data!.id,unit_type:"test",name:`Test ${n}`,sort_order:n,estimated_minutes:30}))).select("id");units=us.data!.map(x=>x.id);
  const plan=await a.from("weekly_plans").insert({user_id:ua.id,exam_profile_id:profile,week_start_date:"2026-08-03",week_end_date:"2026-08-09",available_minutes:600,planning_budget_minutes:510,planned_minutes:120,status:"active",generation_version:1}).select("id").single();
  const tasks=await a.from("tasks").insert([
   {user_id:ua.id,exam_profile_id:profile,weekly_plan_id:plan.data!.id,subject_id:MATH,curriculum_node_id:TOPIC,task_type:"learn_topic",title:"Learn",planned_date:"2026-08-08",estimated_minutes:60,importance:"important",priority_score:40,status:"ready",source_reason:"curriculum_progress",dedupe_key:"p4-learn"},
   {user_id:ua.id,exam_profile_id:profile,weekly_plan_id:plan.data!.id,subject_id:MATH,curriculum_node_id:TOPIC,resource_id:resource,task_type:"solve_resource_units",title:"Solve",planned_date:"2026-08-08",estimated_minutes:60,importance:"important",priority_score:45,status:"ready",source_reason:"resource_progress",dedupe_key:"p4-solve"}
  ]).select("id,task_type"); learn=tasks.data!.find(x=>x.task_type==="learn_topic")!.id;solve=tasks.data!.find(x=>x.task_type==="solve_resource_units")!.id;
  await a.from("task_progress").insert([{task_id:learn,user_id:ua.id},{task_id:solve,user_id:ua.id}]);
  await a.from("task_resource_units").insert(units.map(id=>({user_id:ua.id,task_id:solve,resource_unit_id:id})));
  const otherRes=await a.from("resources").insert({user_id:ua.id,exam_profile_id:profile,subject_id:MATH,name:"Other Test Book",resource_type:"question_bank",resource_role:"reinforcement",difficulty:"normal",status:"active"}).select("id").single();otherResource=otherRes.data!.id;
  const otherSec=await a.from("resource_sections").insert({resource_id:otherResource,curriculum_node_id:TOPIC,name:"Other",sort_order:1}).select("id").single();
  const otherUnitResult=await a.from("resource_units").insert({resource_id:otherResource,resource_section_id:otherSec.data!.id,unit_type:"test",name:"Other Test",sort_order:1,estimated_minutes:20}).select("id").single();otherUnit=otherUnitResult.data!.id;
  const otherTask=await a.from("tasks").insert({user_id:ua.id,exam_profile_id:profile,weekly_plan_id:plan.data!.id,subject_id:MATH,curriculum_node_id:TOPIC,resource_id:otherResource,task_type:"solve_resource_units",title:"Other Solve",planned_date:"2026-08-08",estimated_minutes:20,importance:"optional",priority_score:10,status:"ready",source_reason:"resource_progress",dedupe_key:"p4-other-solve"}).select("id").single();otherSolve=otherTask.data!.id;
  await a.from("task_progress").insert({task_id:otherSolve,user_id:ua.id});
  await a.from("task_resource_units").insert({user_id:ua.id,task_id:otherSolve,resource_unit_id:otherUnit});
 });

 it("starts one live task session and rejects a second",async()=>{const s=await a.rpc("start_study_session",{p_task_id:learn,p_entry_source:"web"});expect(s.error).toBeNull();session=s.data.id;const second=await a.rpc("start_study_session",{p_task_id:solve,p_entry_source:"web"});expect(second.error?.message).toContain("ACTIVE_SESSION_EXISTS");});
 it("isolates session and mutation from User B",async()=>{expect((await b.from("study_sessions").select("id").eq("id",session)).data).toEqual([]);expect((await b.rpc("finish_study_session",{p_session_id:session})).error).not.toBeNull();});
 it("finishes with server duration, advances task remaining time and double finish is idempotent",async()=>{const first=await a.rpc("finish_study_session",{p_session_id:session});expect(first.error).toBeNull();expect(first.data.duration_minutes).toBe(1);const second=await a.rpc("finish_study_session",{p_session_id:session});expect(second.data.duration_minutes).toBe(1);const tp=await a.from("task_progress").select("actual_study_minutes,completed_minutes").eq("task_id",learn).single();expect(tp.data!.actual_study_minutes).toBe(1);expect(tp.data!.completed_minutes).toBe(1);expect((await a.from("tasks").select("status").eq("id",learn).single()).data!.status).toBe("partially_completed");const topic=await a.from("topic_progress").select("total_study_minutes").eq("exam_profile_id",profile).eq("curriculum_node_id",TOPIC).single();expect(topic.data!.total_study_minutes).toBe(1);});
 it("does not allow a completed task to be restarted from a stale Telegram or web button",async()=>{const completed=await a.rpc("update_task_progress",{p_task_id:learn,p_completed_minutes:60});expect(completed.error).toBeNull();expect(completed.data.status).toBe("completed");const restart=await a.rpc("start_study_session",{p_task_id:learn,p_entry_source:"web"});expect(restart.error?.message).toContain("TASK_NOT_STARTABLE");});
 it("records retroactive minutes and excludes cancelled sessions",async()=>{const retro=await a.rpc("record_retroactive_session",{p_payload:{examProfileId:profile,subjectId:MATH,curriculumNodeId:TOPIC,durationMinutes:80,endedAt:"2026-08-02T12:00:00Z",entrySource:"retroactive"}});expect(retro.error).toBeNull();const active=await a.rpc("start_study_session",{p_task_id:solve,p_entry_source:"web"});const cancelled=await a.rpc("cancel_study_session",{p_session_id:active.data.id});expect(cancelled.data.status).toBe("cancelled");const topic=await a.from("topic_progress").select("total_study_minutes").eq("exam_profile_id",profile).eq("curriculum_node_id",TOPIC).single();expect(topic.data!.total_study_minutes).toBe(81);});
 it("rejects web and Telegram overlap without side effects and allows a touching boundary",async()=>{
  const base={examProfileId:profile,subjectId:MATH,curriculumNodeId:TOPIC,durationMinutes:50,endedAt:"2026-08-02T14:00:00Z",entrySource:"retroactive"};
  const first=await a.rpc("record_retroactive_session",{p_payload:base});expect(first.error).toBeNull();
  const beforeSessions=(await a.from("study_sessions").select("id",{count:"exact",head:true})).count;
  const beforeTopic=(await a.from("topic_progress").select("total_study_minutes").eq("exam_profile_id",profile).eq("curriculum_node_id",TOPIC).single()).data!.total_study_minutes;
  const beforeTask=(await a.from("task_progress").select("completed_minutes,actual_study_minutes").eq("task_id",otherSolve).single()).data;
  const full=await a.rpc("record_retroactive_session",{p_payload:{...base,taskId:otherSolve}});expect(full.error?.message).toContain("SESSION_TIME_OVERLAP");
  const partial=await a.rpc("record_retroactive_session",{p_payload:{...base,taskId:otherSolve,durationMinutes:30,endedAt:"2026-08-02T14:15:00Z"}});expect(partial.error?.message).toContain("SESSION_TIME_OVERLAP");
  const telegram=await admin.rpc("telegram_record_retroactive_session",{p_user_id:ua.id,p_payload:{...base,taskId:otherSolve,durationMinutes:20,endedAt:"2026-08-02T13:20:00Z"}});expect(telegram.error?.message).toContain("SESSION_TIME_OVERLAP");
  expect((await a.from("study_sessions").select("id",{count:"exact",head:true})).count).toBe(beforeSessions);
  expect((await a.from("topic_progress").select("total_study_minutes").eq("exam_profile_id",profile).eq("curriculum_node_id",TOPIC).single()).data!.total_study_minutes).toBe(beforeTopic);
  expect((await a.from("task_progress").select("completed_minutes,actual_study_minutes").eq("task_id",otherSolve).single()).data).toEqual(beforeTask);
  const touching=await a.rpc("record_retroactive_session",{p_payload:{...base,durationMinutes:20,endedAt:"2026-08-02T13:10:00Z"}});expect(touching.error).toBeNull();
 });
 it("records valid D/Y/B, updates counters and makes task partial",async()=>{const key=`result-${randomUUID()}`;const r=await a.rpc("record_test_result",{p_payload:{examProfileId:profile,taskId:solve,subjectId:MATH,curriculumNodeId:TOPIC,resourceId:resource,resourceUnitId:units[0],correct:20,wrong:5,blank:0,total:25,entrySource:"web",idempotencyKey:key}});expect(r.error).toBeNull();resultId=r.data.id;expect(Number(r.data.accuracy)).toBeCloseTo(.8);expect(r.data.review_status).toBe("pending");const task=await a.from("tasks").select("status").eq("id",solve).single();expect(task.data!.status).toBe("partially_completed");const duplicate=await a.rpc("record_test_result",{p_payload:{examProfileId:profile,taskId:solve,subjectId:MATH,curriculumNodeId:TOPIC,resourceId:resource,resourceUnitId:units[0],correct:20,wrong:5,blank:0,total:25,entrySource:"web",idempotencyKey:key}});expect(duplicate.data.id).toBe(resultId);expect((await a.from("test_results").select("id",{count:"exact",head:true}).eq("idempotency_key",key)).count).toBe(1);});
 it("rejects invalid totals",async()=>{const r=await a.rpc("record_test_result",{p_payload:{examProfileId:profile,subjectId:MATH,correct:10,wrong:2,blank:0,total:10}});expect(r.error?.message).toContain("INVALID_TEST_RESULT");});
 it("rejects a resource unit linked to a different task",async()=>{const key=`mismatch-${randomUUID()}`;const r=await a.rpc("record_test_result",{p_payload:{examProfileId:profile,taskId:solve,subjectId:MATH,curriculumNodeId:TOPIC,resourceId:otherResource,resourceUnitId:otherUnit,correct:10,wrong:0,blank:0,total:10,entrySource:"web",idempotencyKey:key}});expect(r.error?.message).toContain("RESOURCE_UNIT_NOT_LINKED_TO_TASK");expect((await a.from("test_results").select("id",{count:"exact",head:true}).eq("idempotency_key",key)).count).toBe(0);});
 it("last unit result completes resource unit and task",async()=>{const r=await a.rpc("record_test_result",{p_payload:{examProfileId:profile,taskId:solve,subjectId:MATH,curriculumNodeId:TOPIC,resourceId:resource,resourceUnitId:units[1],correct:10,wrong:0,blank:0,total:10,entrySource:"web",idempotencyKey:`result-${randomUUID()}`}});expect(r.error).toBeNull();expect((await a.from("tasks").select("status").eq("id",solve).single()).data!.status).toBe("completed");expect((await a.from("resource_unit_progress").select("id",{count:"exact",head:true}).in("resource_unit_id",units)).count).toBe(2);});
 it("corrects topic counters atomically",async()=>{const before=await a.from("topic_progress").select("correct_questions,wrong_questions,total_questions").eq("exam_profile_id",profile).eq("curriculum_node_id",TOPIC).single();const updated=await a.rpc("update_test_result",{p_result_id:resultId,p_correct:21,p_wrong:4,p_blank:0,p_total:25,p_duration:null});expect(updated.error).toBeNull();const after=await a.from("topic_progress").select("correct_questions,wrong_questions,total_questions").eq("exam_profile_id",profile).eq("curriculum_node_id",TOPIC).single();expect(after.data!.correct_questions).toBe(before.data!.correct_questions+1);expect(after.data!.wrong_questions).toBe(before.data!.wrong_questions-1);expect(after.data!.total_questions).toBe(before.data!.total_questions);});
 it("isolates results and supports idempotent wrong review",async()=>{expect((await b.from("test_results").select("id").eq("id",resultId)).data).toEqual([]);expect((await b.rpc("review_test_result",{p_result_id:resultId})).error).not.toBeNull();const one=await a.rpc("review_test_result",{p_result_id:resultId});const two=await a.rpc("review_test_result",{p_result_id:resultId});expect(one.data.review_status).toBe("reviewed");expect(two.data.review_status).toBe("reviewed");});
 it("stores only token hashes and enforces global Telegram identity uniqueness",async()=>{const raw=`raw-${randomUUID()}`,hash=`sha256-${randomUUID()}`;await a.from("messaging_link_tokens").insert({user_id:ua.id,provider:"telegram",token_hash:hash,expires_at:new Date(Date.now()+600000).toISOString()});const row=await a.from("messaging_link_tokens").select("token_hash").eq("token_hash",hash).single();expect(row.data!.token_hash).toBe(hash);expect(JSON.stringify(row.data)).not.toContain(raw);await a.from("messaging_identities").insert({user_id:ua.id,provider:"telegram",external_user_id:"tg-unique",external_chat_id:"chat-a"});const duplicate=await b.from("messaging_identities").insert({user_id:ub.id,provider:"telegram",external_user_id:"tg-unique",external_chat_id:"chat-b"});expect(duplicate.error).not.toBeNull();});
});
