import { randomUUID } from "node:crypto";
import { createClient } from "@supabase/supabase-js";
import { readLocalSupabaseStatus } from "./supabase-status.mjs";

const EDITION="11000000-0000-0000-0000-000000000001",MATH="20000000-0000-0000-0000-000000000002",TOPIC="30000000-0000-0000-0000-000000000001";const{url,anonKey}=readLocalSupabaseStatus();
async function actor(label){const api=createClient(url,anonKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}),id=randomUUID(),signup=await api.auth.signUp({email:`v1-${label}-${id}@example.test`,password:`Safe-${id}`});if(signup.error)throw signup.error;return{api,user:signup.data.user.id,token:signup.data.session.access_token};}
const a=await actor("a"),b=await actor("b");const profile=await a.api.from("exam_profiles").insert({user_id:a.user,exam_edition_id:EDITION,preparation_start_date:"2026-08-01",target_exam_date:"2027-08-01",status:"active"}).select("id").single();if(profile.error)throw profile.error;await a.api.from("user_subjects").insert({user_id:a.user,exam_profile_id:profile.data.id,subject_id:MATH,status:"active"});await a.api.rpc("initialize_subject_progress",{p_exam_profile_id:profile.data.id,p_subject_id:MATH});await a.api.from("weekly_availability").insert(Array.from({length:7},(_,i)=>({user_id:a.user,exam_profile_id:profile.data.id,weekday:i+1,start_time:"09:00",end_time:"18:00"})));const resource=await a.api.from("resources").insert({user_id:a.user,exam_profile_id:profile.data.id,subject_id:MATH,name:"V1 Pilot Kitabı",resource_type:"question_bank",resource_role:"primary",difficulty:"normal",status:"active"}).select("id").single();const section=await a.api.from("resource_sections").insert({resource_id:resource.data.id,curriculum_node_id:TOPIC,name:"Temel Kavramlar",sort_order:1}).select("id").single();const unit=await a.api.from("resource_units").insert({resource_id:resource.data.id,resource_section_id:section.data.id,unit_type:"test",name:"V1 Test",sort_order:1,question_count:20,estimated_minutes:20}).select("id").single();
const base=`${url}/functions/v1/app-api`;async function http(actor,path,{method="GET",body}={}){const response=await fetch(`${base}${path}`,{method,headers:{Authorization:`Bearer ${actor.token}`,apikey:anonKey,"Content-Type":"application/json"},body:body===undefined?undefined:JSON.stringify(body)});const payload=await response.json();if(!response.ok)throw new Error(`${path}:${response.status}:${JSON.stringify(payload)}`);return payload;}
const built=await http(a,"/weekly-plan/build",{method:"POST"});const solve=built.tasks.find(task=>task.task_type==="solve_resource_units");if(!solve)throw new Error("resource task missing");const next=await http(a,"/tasks/next");if(!next.task?.id)throw new Error("next best missing");const started=await http(a,"/study-sessions/start",{method:"POST",body:{taskId:solve.id}});const finished=await http(a,`/study-sessions/${started.id}/finish`,{method:"POST"});if(finished.status!=="completed")throw new Error("study session failed");const result=await http(a,"/test-results",{method:"POST",body:{taskId:solve.id,subjectId:MATH,curriculumNodeId:TOPIC,resourceId:resource.data.id,resourceUnitId:unit.data.id,correct:8,wrong:12,blank:0,total:20,idempotencyKey:`v1-${randomUUID()}`}});if(!result.mastery?.assessment||!result.mastery?.revision)throw new Error(`mastery/revision missing: ${JSON.stringify(result)}`);const reviewed=await http(a,`/test-results/${result.id}/review`,{method:"POST"});if(reviewed.review_status!=="reviewed")throw new Error("wrong review missing");const revisions=await http(a,"/revisions?scope=all");if(!revisions.some(row=>row.id===result.mastery.revision.id))throw new Error("revision list missing");
const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul"}).format(new Date());await http(a,"/schedule-exceptions",{method:"POST",body:{date:today,type:"custom",minutesDelta:-450,note:"V1 E2E"}});const replanned=await http(a,"/plans/current/recalculate",{method:"POST",body:{trigger:"capacity_change"}});if(!replanned.revision)throw new Error("dynamic replan missing");const minimum=await http(a,`/plans/minimum-day?date=${today}&availableMinutes=35`);if(minimum.totalMinutes>35)throw new Error("minimum plan budget failed");const projection=await http(a,"/progress/projection");if(!projection.status)throw new Error("projection missing");const report=await http(a,"/reports/weekly/generate",{method:"POST"});if(report.question_count<20||report.actual_minutes<1)throw new Error(`weekly report chain missing: ${JSON.stringify(report)}`);const metrics=await http(a,"/pilot/metrics");if(metrics.next_best_task_usage_count<1||metrics.test_result_count<1||metrics.schedule_exception_count<1||metrics.replan_count<1||metrics.minimum_plan_usage_count<1)throw new Error(`pilot metrics incomplete: ${JSON.stringify(metrics)}`);
const bProfile=await b.api.from("exam_profiles").insert({user_id:b.user,exam_edition_id:EDITION,preparation_start_date:"2026-08-01",status:"active"}).select("id").single();if(bProfile.error)throw bProfile.error;const bReport=await http(b,"/reports/weekly/current");const bMetrics=await http(b,"/pilot/metrics");if(bReport!==null||bMetrics.test_result_count!==0)throw new Error("cross-user report/metrics leak");for(const table of ["weekly_plans","study_sessions","test_results","topic_assessments","revision_schedules","plan_risks","weekly_reports"]){const rows=await b.api.from(table).select("id");if(rows.error||rows.data.length)throw new Error(`User B isolation failed for ${table}`);}
console.log(JSON.stringify({V1_E2E:"PASS",signup:true,examProfile:profile.data.id,resourceUnit:unit.data.id,weeklyPlan:built.plan.id,nextBest:next.reason,studyMinutes:finished.duration_minutes,testResult:result.id,wrongReview:"reviewed",mastery:true,revision:true,scheduleException:true,dynamicReplan:true,minimumPlan:true,projection:projection.status,weeklyReport:report.plan_status,pilotMetrics:true,userBIsolation:true},null,2));
